[tool.isort]
profile = "google"
known_first_party = ["mindmap"]
known_third_party = ["scipy", "numpy", "torch", "matplotlib", "wandb"]
combine_as_imports = true
force_single_line = false
force_sort_within_sections = true
multi_line_output = 3
include_trailing_comma = true
line_length = 100
